=== HugoTejedorArcoitza/sew/xml/circuito.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.uniovi.es"
           xmlns="http://www.uniovi.es"
           elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud_circuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha_carrera" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria_fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="galeria_videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />

	<xs:element name="longitud_circuito">
		<xs:annotation>
			<xs:documentation> La longitud es en kil√≥metros. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="anchura">
		<xs:annotation>
			<xs:documentation> La anchura es en metros </xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="2" />
				<xs:maxInclusive value="25" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="fecha_carrera">
		<xs:simpleType>
			<xs:restriction base="xs:date" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="hora">
		<xs:simpleType>
			<xs:restriction base="xs:time" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="vueltas">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="10" />
				<xs:maxInclusive value="90" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeria_fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="galeria_videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-90" />
				<xs:maxInclusive value="90" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>


	<xs:element name="latitud">
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-180" />
				<xs:maxInclusive value="180" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud">
		<xs:annotation>
			<xs:documentation> La altitud es en metros </xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="0" />
				<xs:maxInclusive value="3000" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== HugoTejedorArcoitza/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>A. Hermanos Rodríguez</nombre>
    <longitud_circuito unidades="kilometros">4.421</longitud_circuito>
    <anchura unidades="metros">15</anchura>
    <fecha_carrera>2024-10-27</fecha_carrera>
    <hora>21:00</hora>
    <vueltas>71</vueltas>
    <localidad>Ciudad de México</localidad>
    <pais>México</pais>
    <referencias>
        <referencia>
            https://www.dazn.com/es-ES/news/motor/autodromo-hermanos-rodriguez-donde-como-caracteristicas-llegar-fotos-escenario-gp-mexico-mundial-f1/mxpvg88ch1as1qky18rqbe3ex</referencia>
        <referencia>https://www.formula1.com/en/racing/2024/mexico</referencia>
        <referencia>
            https://www.caranddriver.com/es/formula-1/calendario/g44472722/formula-1-calendario-2024/</referencia>
    </referencias>
    <galeria_fotografias>
        <fotografia>circuito.jpg</fotografia>
        <fotografia>circuito2.jpg</fotografia>
    </galeria_fotografias>
    <coordenadas>

        <longitud>19.2422</longitud>
        <latitud>-99.0540</latitud>
        <altitud>2231.27</altitud>
    </coordenadas>

    <tramos>
        <tramo>
            <coordenadas>
                <longitud>19.2417</longitud>
                <latitud>-99.0502</latitud>
                <altitud>2231.01</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2417</longitud>
                <latitud>-99.0501</latitud>
                <altitud>2230.96</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2416</longitud>
                <latitud>-99.0501</latitud>
                <altitud>2230.94</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2415</longitud>
                <latitud>-99.0501</latitud>
                <altitud>2231.02</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2414</longitud>
                <latitud>-99.0501</latitud>
                <altitud>2230.98</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2413</longitud>
                <latitud>-99.0501</latitud>
                <altitud>2231.05</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2413</longitud>
                <latitud>-99.0500</latitud>
                <altitud>2231.01</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2412</longitud>
                <latitud>-99.0459</latitud>
                <altitud>2231</altitud>
            </coordenadas>
        </tramo>

        <tramo>
            <coordenadas>
                <longitud>19.2410</longitud>
                <latitud>-99.0459</latitud>
                <altitud>2231.2</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2407</longitud>
                <latitud>-99.0500</latitud>
                <altitud>2226.2</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2353</longitud>
                <latitud>-99.0510</latitud>
                <altitud>2228</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2352</longitud>
                <latitud>-99.0508</latitud>
                <altitud>2229</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2407</longitud>
                <latitud>-99.0500</latitud>
                <altitud>2229</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2349</longitud>
                <latitud>-99.0512</latitud>
                <altitud>2229</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2400</longitud>
                <latitud>-99.0511</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2402</longitud>
                <latitud>-99.0514</latitud>
                <altitud>2228</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2404</longitud>
                <latitud>-99.0515</latitud>
                <altitud>2228</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2405</longitud>
                <latitud>-99.0516</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2406</longitud>
                <latitud>-99.0521</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2406</longitud>
                <latitud>-99.0522</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2408</longitud>
                <latitud>-99.0523</latitud>
                <altitud>2229</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2409</longitud>
                <latitud>-99.0524</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2411</longitud>
                <latitud>-99.0528</latitud>
                <altitud>2228</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2413</longitud>
                <latitud>-99.0541</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2413</longitud>
                <latitud>-99.0542</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2419</longitud>
                <latitud>-99.0542</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2419</longitud>
                <latitud>-99.0543</latitud>
                <altitud>2226</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2418</longitud>
                <latitud>-99.0544</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2418</longitud>
                <latitud>-99.0545</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2413</longitud>
                <latitud>-99.0541</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2419</longitud>
                <latitud>-99.0548</latitud>
                <altitud>2229</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2421</longitud>
                <latitud>-99.0547</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2423</longitud>
                <latitud>-99.0545</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2423</longitud>
                <latitud>-99.0544</latitud>
                <altitud>2227</altitud>
            </coordenadas>
        </tramo>
        <tramo>
            <coordenadas>
                <longitud>19.2417</longitud>
                <latitud>-99.0502</latitud>
                <altitud>2231.01</altitud>
            </coordenadas>
        </tramo>
    </tramos>
</circuito>
